judy/web_app/views.py
from flask import render_template, request, abort, g, Blueprint, jsonify
from judy.web_app.utils import (
    get_heatmap_data,
    get_readable_timestamp,
)

app_bp = Blueprint("judy", __name__)


@app_bp.route("/api/heatmap_data/<run_name>/<groupby>", methods=["GET"])
def fetch_heatmap_data(run_name, groupby):
    df = g.runs_df

    if run_name in df["run"].values:
        filtered_df = df[df["run"] == run_name]
    elif run_name == "all":
        filtered_df = df
    else:
        abort(404)

    data = get_heatmap_data(filtered_df, groupby)

    return jsonify(data)


@app_bp.route("/")
def runs_dashboard():
    all_data = g.all_data
    df = g.runs_df

    combined_run = {
        "name": "All",
        "models": df["model"].nunique(),
        "tasks": df["task"].nunique(),
        "datasets": df["dataset"].nunique(),
        "scenarios": df["scenario"].nunique(),
        "total_eval_num": all_data["total_evaluations"],
    }
    context = {
        "data": all_data["runs"],
        "combined": combined_run,
        "dataframe": df.to_json(orient="records"),
        "scenarios": all_data["data_index"]["scenarios"],
    }
    return render_template("run_dashboard.html", context=context)


@app_bp.route("/about")
def about():
    return render_template("about_page.html", context={})


# not currently in use - might return it later idk?
# @app.route('/models/<model_name>', methods=['GET', 'POST'])
# def model_page(model_name):
#     groupby_options = {
#         'metric_group': 'Metric Group',
#         'run':'Run',
#         'task':'Task',
#         'dataset':'Dataset'
#     }

#     groupby = 'metric_group'
#     if request.method == 'POST':
#         groupby = request.form.get('groupby')

#     if model_name in df['model'].values:
#         filtered_df = df[df['model'] == model_name]
#     else:
#         abort(404)

#     data = get_grouped_df(filtered_df, groupby)

#     run_list = filtered_df['run'].unique()
#     tasks_list = filtered_df['task'].unique()
#     datasets_list = filtered_df['dataset'].unique()

#     context = {
#         'model':model_name,
#         'runs':run_list,
#         'datasets':datasets_list,
#         'tasks':tasks_list,
#         'table_data':data,
#         'groupby':groupby,
#         'groupby_options':groupby_options
#     }


#     return render_template('model_page.html', context=context)
def get_all_items_dict(run_data, data_index):
    item_keys = ["models", "scenarios", "tasks", "datasets"]
    items_dict = {}

    for key in item_keys:
        items_used = f"{key}_used"
        for item_id in run_data[items_used]:
            item_dict = items_dict.get(key, {})
            item_dict[item_id] = data_index[key].get(item_id)
            items_dict[key] = item_dict

    return items_dict


@app_bp.route("/runs/<run_name>", methods=["GET", "POST"])
def run_page(run_name):
    all_data = g.all_data
    df = g.runs_df

    groupby_options = {
        "scenario": "Scenario",
        "task": "Task",
        "dataset": "Dataset",
    }

    groupby = "scenario"
    if request.method == "POST":
        groupby = request.form.get("groupby")

    if run_name in df["run"].values:
        filtered_df = df[df["run"] == run_name]
        run_data = all_data["runs"].get(run_name)

        run_config = run_data["config"]["run"]
        run_configs = {
            "Timestamp": get_readable_timestamp(run_data["metadata"]["timestamp"]),
            "Judge Model": run_config.judge.name,
            "Judge Temperature": run_config.judge.temperature,
            "Random Seed": run_config.random_seed,
            "Total Evaluations": run_data["total_evaluations"],
        }
    elif run_name == "all":
        run_data = all_data
        filtered_df = df
        run_configs = {}
    else:
        abort(404)

    items_dict = get_all_items_dict(run_data, all_data["data_index"])
    data = get_heatmap_data(filtered_df, groupby)
    # we dont actually use the data here (loaded via api)
    # but need to use the keys from the data so we can build out the necessary structure for our heatmaps
    context = {
        "run": run_name,
        "table_keys": data.keys(),
        "groupby": groupby,
        "groupby_options": groupby_options,
        "run_configs": run_configs,
        **items_dict,
    }

    return render_template("run_page.html", context=context)


@app_bp.route("/scenarios")
def scenarios():
    all_data = g.all_data

    item_filter = request.args.get("item")
    seen_scenarios = set()
    scenario_data = []
    for scenario in all_data["data_index"]["scenarios"].values():
        if scenario.id not in seen_scenarios:
            if not item_filter or (item_filter and scenario.id == item_filter):
                seen_scenarios.add(scenario.id)
                scenario_data.append(
                    {
                        "title": scenario.name,
                        "desc": scenario.desc,
                        "links": {"datasets": scenario.datasets},
                    }
                )

    return render_template(
        "card_page.html",
        cards_data=scenario_data,
        page_title="Scenario Info",
        page_subtitle="List of Scenarios used in your Judy Runs",
        page_name="judy.scenarios",
        is_filtered=bool(item_filter),
    )


@app_bp.route("/tasks")
def tasks():
    all_data = g.all_data

    item_filter = request.args.get("item")
    seen_tasks = set()
    task_data = []
    for task in all_data["data_index"]["tasks"].values():
        if task.id not in seen_tasks:
            if not item_filter or (item_filter and task.id == item_filter):
                seen_tasks.add(task.id)
                task_data.append(
                    {
                        "title": task.name,
                        "desc": task.desc,
                        "links": {"tags": task.tags},
                    }
                )

    return render_template(
        "card_page.html",
        cards_data=task_data,
        page_title="Task Info",
        page_subtitle="List of Tasks used in your Judy Runs",
        page_name="judy.tasks",
        is_filtered=bool(item_filter),
    )


@app_bp.route("/datasets")
def datasets():
    all_data = g.all_data

    item_filter = request.args.get("item")

    seen_datasets = set()
    dataset_data = []
    for dataset in all_data["data_index"]["datasets"].values():
        if dataset.id not in seen_datasets:
            if not item_filter or (item_filter and dataset.id == item_filter):
                seen_datasets.add(dataset.id)
                dataset_data.append(
                    {
                        "title": dataset.id,
                        "desc": None,
                        "data": {
                            "Source": dataset.source,
                            "Tags": ", ".join(dataset.tags),
                        },
                        "links": {"tasks": [t.id.value for t in dataset.tasks]},
                    }
                )

    return render_template(
        "card_page.html",
        cards_data=dataset_data,
        page_title="Dataset Info",
        page_subtitle="List of Datasets used in your Judy Runs",
        page_name="judy.datasets",
        is_filtered=bool(item_filter),
    )


@app_bp.route("/models")
def models():
    all_data = g.all_data

    seen_models = set()
    model_data = []
    item_filter = request.args.get("item")
    for model in all_data["data_index"]["models"].values():
        if model.id not in seen_models:
            if not item_filter or (item_filter and model.id == item_filter):
                seen_models.add(model.id)
                model_data.append(
                    {
                        "title": model.id,
                        "desc": None,
                        "data": {
                            "API Type": model.api_type,
                            "Api Base": model.api_base,
                        },
                        "links": {},
                    }
                )

    return render_template(
        "card_page.html",
        cards_data=model_data,
        page_title="Model Info",
        page_subtitle="List of Models used in your Judy Runs",
        page_name="judy.models",
        is_filtered=bool(item_filter),
    )


@app_bp.route("/raw")
@app_bp.route("/raw/<run_name>")
def raw_results(run_name=None):
    all_data = g.all_data
    df = g.runs_df

    model_filter = request.args.get("model")
    dataset_filter = request.args.get("dataset")
    task_filter = request.args.get("task")
    scenario_filter = request.args.get("scenario")

    run_list = df["run"].unique()
    if not run_name:
        run_name = run_list[0]

    run_data = all_data["runs"].get(run_name)
    run_df = df[df["run"] == run_name]

    if not model_filter:
        model_filter = run_df["model"].iloc[0]

    if not scenario_filter:
        scenario_filter = run_df["scenario"].iloc[0]

    if not dataset_filter:
        dataset_filter = run_df[run_df["scenario"] == scenario_filter]["dataset"].iloc[
            0
        ]

    if not task_filter:
        task_filter = run_df[run_df["dataset"] == dataset_filter]["task"].iloc[0]

    results_data = run_data.get("results")
    model_data = results_data.get(model_filter, {})
    if not model_data:
        abort(404)

    scenarios_used = model_data["data"].keys()
    scenario_data = model_data["data"].get(scenario_filter, {})
    datasets_used = scenario_data.keys()

    dataset_data = scenario_data.get(dataset_filter, {})
    dataset = run_data["data_index"]["datasets"].get(dataset_filter, None)
    if not dataset:
        abort(404)

    tasks_used = [ds_task.id.value for ds_task in dataset.tasks]
    filtered_data = dataset_data.get(task_filter, {})
    if not filtered_data:
        abort(404)

    return render_template(
        "raw_results.html",
        runs=run_list,
        run_name=run_name,
        model_name=model_filter,
        dataset_name=dataset_filter,

judy/web_app/templates/about_page.html
{% extends "base.html" %}
{% from "table_macro.html" import table %}
{% block title %}{{context['run']}}{% endblock %}

{% block content %}
<div class="px-4 py-3 my-3 text-center">
  <h1 class="display-5 fw-bold">Judy</h1>
</div>
<div class="row text-center mb-3">
  <p>
    Judy is a python library and framework to evaluate the text-generation capabilities of Large Language Models (LLM) using a Judge LLM.
  </p>
  <p>
    Judy allows users to use a competent Judge LLM (such as GPT-4) to evaluate other LLMs using different options for the following dimensions:
  </p>
  <ul class="no-bullets">
    <li><strong>Dataset: </strong>A source dataset to generate prompts to evaluate models against.</li>
    <li><strong>Task: </strong>A task to evaluate models on. Tasks for judge evaluations have been carefully designed by researchers to assess certain aspects of LLMs.</li>
    <li><strong>Metric: </strong>The metric(s) to use when evaluating the responses from a task. For example - accuracy, level of detail etc.</li>
  </ul>
</div>
{% endblock %}

judy/web_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Judy{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.0/dist/echarts.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="/"><h1>Judy</h1></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Results
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="/">Runs</a></li>
                              <li><a class="dropdown-item" href="{{url_for('judy.raw_results')}}">Raw Results</a></li>
                            </ul>
                          </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('judy.models')}}">Models</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('judy.scenarios')}}">Scenarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('judy.datasets')}}">Datasets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('judy.tasks')}}">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('judy.about')}}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <body>
        <div id="content" class="container">
            {% block content %}{% endblock %}
            <footer class="footer py-5">
                <div class="row">
                    <div class="col">
                        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                            <p>© 2023 Tesserent Innovation. All rights reserved.</p>
                            <div class="col-md-5 offset-md-1 mb-3">
                                <h5>Subscribe to our blog</h5>
                                <p>Learn what's new and exciting from us.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </body>

</body>
</html>

judy/web_app/templates/card_page.html
{% extends "base.html" %}
{% from "info_card.html" import info_card %}

{% block content %}

<div class="container">
    <div class="page-title text-center my-3">
        <h1>{{page_title}}</h1>
        <p>{{page_subtitle}}</p>
    </div>
    {% if is_filtered %}
        <button class="btn btn-outline-primary" id="clear-filter-btn">Show All</button>
    {% endif %}
    <div class="row">
        {% for card in cards_data %}
            <div class="col-md-4">
                {{ info_card(card) }}
            </div>
        {% endfor %}
    </div>
</div>

<script>
    document.getElementById('clear-filter-btn').addEventListener('click', function() {
        window.location.href = "{{url_for(page_name)}}";
    })
</script>

{% endblock %}

judy/web_app/templates/info_card.html
{% macro info_card(card_data) %}
    <div class="card judy-card">
        <div class="card-header">
            {{ card_data.title }}
        </div>
        <div class="card-body">
            {% if card_data.desc %}
            {{ card_data.desc }}
            {% elif card_data.data %}
            <ul>
                {% for key, value in card_data.data.items() %}
                <li><strong>{{key}}: </strong>{{value}}</li>
                {% endfor %}
            </ul>

            {% endif %}
            <hr>
                {% if card_data.links %}
                {% for key, value in card_data.links.items() %}
                    {% if value %}
                        <strong>{{ key }}:</strong>
                        <ul>
                        {% for val in value %}
                            <li><a href="{{url_for('judy.'+key, item=val)}}">{{ val }}</a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
{% endmacro %}

judy/web_app/templates/model_page.html
{% extends "base.html" %}
{% from "table_macro.html" import table %}
{% block title %}{{context['model']}}{% endblock %}

{% block content %}
<div class="container">
    <div class="page-title row text-center mt-3">
        <h1>MODEL: {{context['model']}}</h1>
    </div>
    <hr>
    <div class="row mt-2">
        <div class="col">
            <h2>Runs</h2>
            <ul>
                {% for run in context['runs'] %}
                <li><a href="{{url_for('judy.run_page', run_name=run)}}">{{run}}</a></li>
                {% endfor %}
            </ul>

            <h2>Tasks</h2>
            <ul>
                {% for task in context['tasks'] %}
                <li><a href="{{url_for('judy.grouped_results', group_by='task', filter=task)}}">{{task}}</a></li>
                {% endfor %}
            </ul>


            <h2>Datasets</h2>
            <ul>
                {% for dataset in context['datasets'] %}
                <li><a href="{{url_for('judy.grouped_results', group_by='dataset', filter=dataset)}}">{{dataset}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-9">
            <div class="row">
                <form method="POST">
                    <label for="groupby">Group By</label>
                    <select class="form-select" id="groupby" name="groupby">
                        {% for value, title in context['groupby_options'].items() %}
                            <option value="{{value}}" {% if context['groupby'] == value %}selected{% endif %}>{{title}}</option>
                        {% endfor %}
                    </select>
                    <button class="btn btn-success" type="submit">Confirm</button>
                </form>
            </div>
            <div class="row">
                {{ table(context['table_data'])}}
            </div>
        </div>
    </div>
</div>


{% endblock %}

judy/web_app/templates/raw_results.html
{% extends "base.html" %}

{% block title %}Raw Results{% endblock %}

{% block content %}
<style>
  .eval-content {
    display: none;
  }
  #eval-0 {
    display: block;
  }
</style>
<div class="container">
  <div class="page-title row text-center my-4">
    <h1>Raw Results</h1>
  </div>
  <div class="raw-result-filter-item">
      <div class="col raw-result-filter-group raw-result-filter-item">
        <h5>Run: </h5>
          <div class="dropdown">
          <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdown-runs" data-bs-toggle="dropdown" aria-expanded="false">
            {{ run_name }}
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdown-runs">
            {% for run in runs %}
            <li><a class="dropdown-item" href="{{url_for('judy.raw_results', run_name=run)}}">{{run}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col raw-result-filter-group raw-result-filter-item">
        <h5>Model:</h5>
        <div class="dropdown">
            <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="model-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                {{ model_name }}
            </button>
            <ul class="dropdown-menu" aria-labelledby="model-dropdown">
                {% for model in raw_data["models_used"] %}
                    <li>
                      <a class="dropdown-item" href="{{url_for('judy.raw_results', run_name=run_name, model=model)}}">{{ model }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col raw-result-filter-group raw-result-filter-item">
      <h5>Scenario:</h5>
      <div class="dropdown">
          <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dataset-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
              {{ scenario_name }}
          </button>
          <ul class="dropdown-menu" aria-labelledby="dataset-dropdown">
              {% for scenario in scenarios_used %}
                  <li>
                      <a class="dropdown-item" href="{{url_for('judy.raw_results', run_name=run_name, model=model_name, scenario=scenario)}}">{{ scenario }}</a>
                  </li>
              {% endfor %}
          </ul>
      </div>
  </div>
    <div class="col raw-result-filter-group raw-result-filter-item">
        <h5>Dataset:</h5>
        <div class="dropdown">
            <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dataset-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                {{ dataset_name }}
            </button>
            <ul class="dropdown-menu" aria-labelledby="dataset-dropdown">
                {% for dataset in datasets_used %}
                    <li>
                        <a class="dropdown-item" href="{{url_for('judy.raw_results', run_name=run_name, model=model_name, scenario=scenario_name, dataset=dataset)}}">{{ dataset }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="col raw-result-filter-group raw-result-filter-item">
      <h5>Task:</h5>
      <div class="dropdown">
          <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dataset-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
              {{ task_name }}
          </button>
          <ul class="dropdown-menu" aria-labelledby="dataset-dropdown">
              {% for task in tasks_used %}
                  <li>
                      <a class="dropdown-item" href="{{url_for('judy.raw_results', run_name=run_name, model=model_name, scenario=scenario_name, dataset=dataset_name, task=task)}}">{{ task }}</a>
                  </li>
              {% endfor %}
          </ul>
      </div>
    </div>
  </div>
  <hr>
  <div class="row text-center">
    <span>Total: {{ filtered_data|length }} Evals</span>
  </div>
  <div class="raw-result-filter-item">
    <div class="col raw-result-filter-group raw-result-filter-item" id="eval-buttons">
      <button id="eval-btn-first" class="btn btn-sm btn-outline-primary"><<</button>
      <button id="eval-btn-prev" class="btn btn-sm btn-outline-primary"><</button>
      {% for result in filtered_data %}
        {% if loop.index0 == 0%}
        <span id="eval-idx-{{loop.index0}}" class="current" data-target="{{loop.index0}}">{{ loop.index }}</span>
        {% else %}
        <span id="eval-idx-{{loop.index0}}" class="" data-target="{{loop.index0}}" style="display:none;">{{ loop.index }}</span>
        {% endif %}
      {% endfor %}
      <button id="eval-btn-next" class="btn btn-sm btn-outline-primary">></button>
      <button id="eval-btn-last" class="btn btn-sm btn-outline-primary">>></button>
    </div>
  </div>
  <div class="row">
      <div class="col" >
          {% for result in filtered_data %}
          <div class="eval-content" id="eval-{{loop.index0}}">
            <!-- TODO - add (task name and description) used for this run/dataset/model here -->
            <div class="row">
              <div class="col">
                <div class="accordion" id="response-accordion">

                  {% if result['model'].get('prompt') %}
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="modelPrompt">
                      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseModelPrompt" aria-expanded="true" aria-controls="collapseModelPrompt">
                        <strong>Model Prompt</strong>
                      </button>
                    </h2>
                    <div id="collapseModelPrompt" class="accordion-collapse collapse show" aria-labelledby="modelPrompt" data-bs-parent="#response-accordion">
                      <div class="accordion-body">
                        {{result['model']['prompt']}}
                      </div>
                    </div>
                  </div>
                  {% endif %}

                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingContext">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseContext" aria-expanded="false" aria-controls="collapseContext">
                        <strong>Model Response</strong>
                      </button>
                    </h2>
                    <div id="collapseContext" class="accordion-collapse collapse" aria-labelledby="headingContext" data-bs-parent="#response-accordion">
                      <div class="accordion-body">
                        <strong>Response: </strong>{{result['model']['response']}}
                        {% if result['model'].get('answer') %}
                        <hr>
                        <strong>Ground Truth: </strong>{{result['model']['answer']}}
                        {% endif %}
                      </div>
                    </div>
                  </div>

                </div>

              </div>
              <div class="col">
                <div class="accordion" id="results-accordion">

                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingScores">
                      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseScores" aria-expanded="true" aria-controls="collapseScores">
                        <strong>Evaluation Metrics</strong>
                      </button>
                    </h2>
                    <div id="collapseScores" class="accordion-collapse collapse show" aria-labelledby="headingScores" data-bs-parent="#results-accordion">
                      <div class="accordion-body">
                        <ul>
                          {% for metric_score in result['evaluator']['scores'] %}
                            <li><strong>{{metric_score['name']}}: </strong>{{metric_score['score']}}</li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingResults">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseResponse" aria-expanded="false" aria-controls="collapseResponse">
                      <strong>Evaluation Results</strong>
                      </button>
                    </h2>
                    <div id="collapseResponse" class="accordion-collapse collapse" aria-labelledby="headingResults" aria-expanded="false" data-bs-parent="#results-accordion">
                      <div class="accordion-body" style="white-space: pre-line;">
                        {{result['evaluator']['response']}}
                      </div>
                    </div>
                  </div>

                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingPrompt">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePrompt" aria-expanded="false" aria-controls="collapsePrompt">
                      <strong>Evaluation Prompt</strong>
                      </button>
                    </h2>
                    <div id="collapsePrompt" class="accordion-collapse collapse" aria-labelledby="headingPrompt" data-bs-parent="#results-accordion">
                      <div class="accordion-body" style="white-space: pre-line;">
                        {{result['evaluator']['prompt']}}
                      </div>
                    </div>
                  </div>

                </div>

              </div>
            </div>
          </div>
          {% endfor %}
      </div>
  </div>
</div>
<script>

  // Select the div with the ID "eval-buttons"
  const evalButtonsDiv = document.getElementById("eval-buttons");

  // Select all buttons within the "eval-buttons" div
  const buttonsInEval = evalButtonsDiv.querySelectorAll("button");

  const spansInEval = evalButtonsDiv.querySelectorAll("span");
  const totalEvals = spansInEval.length;

  // Implement a basic pagination bar for evals
  buttonsInEval.forEach(button => {
      button.addEventListener('click', () => {
          const currentTargetId = +evalButtonsDiv.querySelector("span.current").getAttribute("data-target");
          var targetId = null;
          // Get the target div's ID from the data attribute
          if (button.id === "eval-btn-first") {
            targetId = 0;
          }
          else if (button.id === "eval-btn-prev") {
            if (currentTargetId === 0) {
              targetId = 0;
            }
            else {
              targetId = currentTargetId - 1;
            }
          }
          else if (button.id === "eval-btn-next") {
            if (currentTargetId === totalEvals - 1) {
              targetId = totalEvals - 1;
            }
            else {
              targetId = currentTargetId + 1;
            }
          }
          else if (button.id === "eval-btn-last") {
            targetId = totalEvals - 1;
          }

          // Hide all divs
          document.querySelectorAll('.eval-content').forEach(div => {
              div.style.display = 'none';
          });

          // Show the target div
          document.getElementById("eval-" + targetId).style.display = 'block';

          // Show the target eval number
          spansInEval.forEach(spn => {
            if (spn.id === "eval-idx-" + targetId) {
              spn.classList = ["current"]
              spn.style.display = 'block';
            }
            else {
              spn.classList = []
              spn.style.display = 'none';
            }
          });
      });
  });
</script>
{% endblock %}

judy/web_app/templates/table_macro.html
{% macro table(table_data, context) %}
    {% set groupby = context["groupby"] %}
    {% set context_key = groupby + 's' %}
    {% for title, data in table_data.items() %}
    {% if context[context_key].get(title) %}
    <div class="table-container">
        <h4>{{ context[context_key][title].name or context[context_key][title].id }}</h4>
        <table class="table table-bordered results-table">
            <thead class="table-light">
                <tr>
                    {% if groupby != 'model' %}
                        <th>Model</th>
                    {% endif %}
                    {% for metric in data.columns %}
                        <th>{{ metric }}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% for model, row in data.iterrows() %}
                <tr>
                    {% if groupby != 'model' %}
                        <td>{{model}}</td>
                    {% endif %}
                    {% for _, value in row.items() %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
    {% endif %}
    {% endfor %}
{% endmacro %}